[build]
builder = "nixpacks"
buildCommand = "npm install && npm install --workspace=backend && npm run build --workspace=frontend"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyMaxRetries = 5
